In [3]:
#Arrays

import numpy

def array(arr):
    a1=numpy.array(arr, dtype = float)
    a2=numpy.array(arr[::-1], dtype = float)
    return a2

arr=input().strip().split(' ')
result=array(arr)
print(result)

1 2 3 4 5 -8
[-8.  5.  4.  3.  2.  1.]


In [7]:
#Shape and Reshape

l=numpy.array(input().split(' '), int)
print(l.reshape(2,2))

1 2 3 4
[[1 2]
 [3 4]]


In [9]:
#transose and flatten

a, b=map(int, input().split())
storage =numpy.array([input().strip().split() for i in range(a)], int )
print(storage.transpose())
print(storage.flatten())

 2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [16]:
#concatinate

import numpy

a,b,c = map(int, input().split())
n=[list(map(int,input().split())) for i in range(a)]
m =[list(map(int,input().split())) for i in range(b)]
k=numpy.array(n)
p=numpy.array(m)

print (numpy.concatenate((k,p),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [19]:
#zeros and ones

import numpy

size = tuple (map(int, input().strip().split()))
print( numpy.zeros(size,int))
print(numpy.ones(size, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [25]:
#eye and identity

import numpy
numpy.set_printoptions(sign=' ')

a,b=map(int, input().split())
eye=numpy.eye(a,b)
print(eye)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [26]:
#array mathematics 

import numpy
def arrays(arr, arr1, arr2):
    arr = numpy.array(arr, dtype = int)
    arr1 = numpy.array([arr1], dtype = int)
    arr2 = numpy.array([arr2], dtype = int)

    add = numpy.add(arr1,arr2)
    sub = numpy.subtract(arr1, arr2)
    mul = numpy.multiply(arr1, arr2)
    div = numpy.floor_divide(arr1, arr2)
    mod = numpy.mod(arr1, arr2)
    power = numpy.power(arr1, arr2)
    return add,sub,mul,div,mod,power

arr = input().strip().split(' ')

arr1 = input().strip().split(' ')
arr2 = input().strip().split(' ')
add,sub,mul,div,mod,power = arrays(arr, arr1, arr2)
print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(power)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [1]:
#floor, ceil and rint

import numpy

fcr=numpy.array(input().split(), float)
print(numpy.floor(fcr))
print(numpy.ceil(fcr))
print(numpy.rint(fcr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [10]:
#sum and prod

import numpy

a,b=map(int, input().split())
arr = numpy.array([input().split() for i in range(a)], int)
print(numpy.prod(numpy.sum(array,axis=0),axis = None))

2 2
1 2
3 4
24


In [11]:
#min and max

a,b=map(int,input().split())
mm=numpy.array([input().split() for i in range(a)],dtype = int)
print(numpy.max(numpy.min(mm, axis=1),axis=0))

4 2
2 5
3 7
1 3
4 0
3


In [14]:
#mean, var and std

a,b=map(int,input().split(" "))
mvs=numpy.array([input().split() for i in range(a)], int)
print(numpy.mean(mvs, axis =1))
print(numpy.var(mvs, axis = 0))
print(round(numpy.std(mvs, axis = None),11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


In [15]:
#dot and cross

import numpy

dc= int(input())
a=numpy.array([input().split() for i in range(dc)], int)
b=numpy.array([input().split() for i in range(dc)], int)
print(numpy.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [16]:
#inner and outer

i = numpy.array(input().split(), int)
o = numpy.array(input().split(), int)

print(numpy.inner(i,o))
print(numpy.outer(i,o))

0 1
2 3
3
[[0 0]
 [2 3]]


In [17]:
#polynomials

print(numpy.polyval(numpy.array(input().split(),float),int (input())))

1.1 2 3
0
3.0


In [18]:
#linear algebra

print(round(numpy.linalg.det(numpy.array([input().split() for i in range(int(input()))], float)),2))

2
1.1 1.1
1.1 1.1
0.0
